# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
require 'dotenv'
Dotenv.load

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "8 Ball.xcodeproj")
    build_app(
      scheme: "8 Ball",
      export_options: {
        provisioningProfiles: {
          "net.phor.--Ball66" => "match AppStore net.phor.--Ball66",
          "net.phor.--Ball66.watchkitapp" => "match AppStore net.phor.--Ball66.watchkitapp"
        }
      },
      include_bitcode: true,
      export_method: "app-store"
    )
    upload_to_app_store
  end
end
